added error message if apt-get fails

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -32,8 +32,8 @@ cd $CACHE_DIR
 needed=( libsasl2-dev libsasl2-modules-gssapi-mit libssl-dev zlib )
 missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
 if [[ "$missing" ]]; then
-    apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-    apt-get install -q -y $missing
+    # apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+    apt-get install -q -y $missing || { echo "Failed to 'apt-get install'. You must build this formula using Docker."; exit 1; }
 fi
 
 # remove old, pre-installed librdkafka during this build, it'll be there again once slug is deployed
